name: twitter-adaptor
description: testing twitter

node_identifier: taexample

platforms:
  - Docker

data_sources:
  - name: min-api.cryptocompare
    url: https://min-api.cryptocompare.com/data/price

parameters:
  - from
  - to